// <auto-generated />
using System;
using Api_ProjectManagement.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api_ProjectManagement.Migrations
{
    [DbContext(typeof(ProjectManagementDBContext))]
    [Migration("20230719203058_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Api_ProjectManagement.Models.Archivo", b =>
                {
                    b.Property<int>("IdArchivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdArchivo"), 1L, 1);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UrlArchivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("IdArchivo")
                        .HasName("PK__Archivos__26B92111915179D8");

                    b.ToTable("Archivos");
                });

            modelBuilder.Entity("Api_ProjectManagement.Models.Comentario", b =>
                {
                    b.Property<int>("IdComentario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdComentario"), 1L, 1);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<int?>("IdArchivo")
                        .HasColumnType("int");

                    b.Property<int?>("IdTarea")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdComentario")
                        .HasName("PK__Comentar__DDBEFBF98A3FB52C");

                    b.HasIndex("IdArchivo");

                    b.HasIndex("IdTarea");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Comentarios");
                });

            modelBuilder.Entity("Api_ProjectManagement.Models.Estado", b =>
                {
                    b.Property<int>("IdEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstado"), 1L, 1);

                    b.Property<string>("Nombre")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdEstado")
                        .HasName("PK__Estado__FBB0EDC174FEDBD8");

                    b.HasIndex(new[] { "Nombre" }, "UQ__Estado__75E3EFCF28CFE0B4")
                        .IsUnique()
                        .HasFilter("[Nombre] IS NOT NULL");

                    b.ToTable("Estado", (string)null);
                });

            modelBuilder.Entity("Api_ProjectManagement.Models.HistorialTarea", b =>
                {
                    b.Property<int>("IdHistorialTarea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHistorialTarea"), 1L, 1);

                    b.Property<DateTime?>("FechaCambio")
                        .HasColumnType("datetime");

                    b.Property<int?>("IdEstadoNuevo")
                        .HasColumnType("int");

                    b.Property<int?>("IdTarea")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdHistorialTarea")
                        .HasName("PK__Historia__7A8790175C09C187");

                    b.HasIndex("IdTarea");

                    b.HasIndex("IdUsuario");

                    b.ToTable("HistorialTareas");
                });

            modelBuilder.Entity("Api_ProjectManagement.Models.Prioridad", b =>
                {
                    b.Property<int>("IdPrioridad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPrioridad"), 1L, 1);

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdPrioridad")
                        .HasName("PK__Priorida__0FC70DD51699884F");

                    b.HasIndex(new[] { "Nombre" }, "UQ__Priorida__75E3EFCF523FD037")
                        .IsUnique()
                        .HasFilter("[Nombre] IS NOT NULL");

                    b.ToTable("Prioridad", (string)null);
                });

            modelBuilder.Entity("Api_ProjectManagement.Models.Proyecto", b =>
                {
                    b.Property<int>("IdProyecto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProyecto"), 1L, 1);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("FechaInicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("IdEstado")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdProyecto")
                        .HasName("PK__Proyecto__F4888673C879F5DA");

                    b.HasIndex("IdEstado");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Proyectos");
                });

            modelBuilder.Entity("Api_ProjectManagement.Models.ProyectoUsuario", b =>
                {
                    b.Property<int>("IdProyectoUsuarios")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProyectoUsuarios"), 1L, 1);

                    b.Property<bool?>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<int?>("IdProyecto")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdProyectoUsuarios")
                        .HasName("PK__Proyecto__EFCF35317220DAE9");

                    b.HasIndex("IdProyecto");

                    b.HasIndex("IdUsuario");

                    b.ToTable("ProyectoUsuarios");
                });

            modelBuilder.Entity("Api_ProjectManagement.Models.Role", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"), 1L, 1);

                    b.Property<bool?>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdRol")
                        .HasName("PK__Roles__2A49584CA6E9E677");

                    b.HasIndex(new[] { "Nombre" }, "UQ__Roles__75E3EFCF8BD76D68")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Api_ProjectManagement.Models.Tarea", b =>
                {
                    b.Property<int>("IdTarea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTarea"), 1L, 1);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaInicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("IdArchivo")
                        .HasColumnType("int");

                    b.Property<int?>("IdEstado")
                        .HasColumnType("int");

                    b.Property<int?>("IdPrioridad")
                        .HasColumnType("int");

                    b.Property<int?>("IdProyecto")
                        .HasColumnType("int");

                    b.Property<int?>("IdTareaPadre")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IdTarea")
                        .HasName("PK__Tareas__EADE909808C2F6F3");

                    b.HasIndex("IdArchivo");

                    b.HasIndex("IdEstado");

                    b.HasIndex("IdPrioridad");

                    b.HasIndex("IdProyecto");

                    b.HasIndex("IdTareaPadre");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Tareas");
                });

            modelBuilder.Entity("Api_ProjectManagement.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"), 1L, 1);

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Contrasenia")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("Foto")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdUsuario")
                        .HasName("PK__Usuarios__5B65BF97342D1871");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Api_ProjectManagement.Models.UsuariosRole", b =>
                {
                    b.Property<int>("IdUsuarioRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuarioRol"), 1L, 1);

                    b.Property<int?>("IdRol")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdUsuarioRol")
                        .HasName("PK__Usuarios__6806BF4AB664B3D5");

                    b.HasIndex("IdRol");

                    b.HasIndex("IdUsuario");

                    b.ToTable("UsuariosRoles");
                });

            modelBuilder.Entity("Api_ProjectManagement.Models.Comentario", b =>
                {
                    b.HasOne("Api_ProjectManagement.Models.Archivo", "IdArchivoNavigation")
                        .WithMany("Comentarios")
                        .HasForeignKey("IdArchivo")
                        .HasConstraintName("Fk_Comentario_Refe_Archivo");

                    b.HasOne("Api_ProjectManagement.Models.Tarea", "IdTareaNavigation")
                        .WithMany("Comentarios")
                        .HasForeignKey("IdTarea")
                        .HasConstraintName("Fk_Comentario_Refe_Tarea");

                    b.HasOne("Api_ProjectManagement.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("Comentarios")
                        .HasForeignKey("IdUsuario")
                        .HasConstraintName("Fk_Comentario_Refe_Usuario");

                    b.Navigation("IdArchivoNavigation");

                    b.Navigation("IdTareaNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("Api_ProjectManagement.Models.HistorialTarea", b =>
                {
                    b.HasOne("Api_ProjectManagement.Models.Tarea", "IdTareaNavigation")
                        .WithMany("HistorialTareas")
                        .HasForeignKey("IdTarea")
                        .HasConstraintName("Fk_HistorialTareas_Refe_Tarea");

                    b.HasOne("Api_ProjectManagement.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("HistorialTareas")
                        .HasForeignKey("IdUsuario")
                        .HasConstraintName("Fk_HistorialTareas_Refe_Usuario");

                    b.Navigation("IdTareaNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("Api_ProjectManagement.Models.Proyecto", b =>
                {
                    b.HasOne("Api_ProjectManagement.Models.Estado", "IdEstadoNavigation")
                        .WithMany("Proyectos")
                        .HasForeignKey("IdEstado")
                        .HasConstraintName("Fk_Proyecto_Refe_Estado");

                    b.HasOne("Api_ProjectManagement.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("Proyectos")
                        .HasForeignKey("IdUsuario")
                        .HasConstraintName("Fk_Proyecto_Refe_Usuario");

                    b.Navigation("IdEstadoNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("Api_ProjectManagement.Models.ProyectoUsuario", b =>
                {
                    b.HasOne("Api_ProjectManagement.Models.Proyecto", "IdProyectoNavigation")
                        .WithMany("ProyectoUsuarios")
                        .HasForeignKey("IdProyecto")
                        .HasConstraintName("Fk_royectoUsuarios_Refe_Proyectos");

                    b.HasOne("Api_ProjectManagement.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("ProyectoUsuarios")
                        .HasForeignKey("IdUsuario")
                        .HasConstraintName("Fk_ProyectoUsuarios_Refe_Usuario");

                    b.Navigation("IdProyectoNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("Api_ProjectManagement.Models.Tarea", b =>
                {
                    b.HasOne("Api_ProjectManagement.Models.Archivo", "IdArchivoNavigation")
                        .WithMany("Tareas")
                        .HasForeignKey("IdArchivo")
                        .HasConstraintName("Fk_Tareas_Refe_Archivos");

                    b.HasOne("Api_ProjectManagement.Models.Estado", "IdEstadoNavigation")
                        .WithMany("Tareas")
                        .HasForeignKey("IdEstado")
                        .HasConstraintName("Fk_Tareas_Refe_Estado");

                    b.HasOne("Api_ProjectManagement.Models.Prioridad", "IdPrioridadNavigation")
                        .WithMany("Tareas")
                        .HasForeignKey("IdPrioridad")
                        .HasConstraintName("Fk_Tareas_Refe_Prioridad");

                    b.HasOne("Api_ProjectManagement.Models.Proyecto", "IdProyectoNavigation")
                        .WithMany("Tareas")
                        .HasForeignKey("IdProyecto")
                        .HasConstraintName("Fk_Tareas_Refe_Proyecto");

                    b.HasOne("Api_ProjectManagement.Models.Tarea", "IdTareaPadreNavigation")
                        .WithMany("InverseIdTareaPadreNavigation")
                        .HasForeignKey("IdTareaPadre")
                        .HasConstraintName("Fk_Tareas_Refe_Tareas");

                    b.HasOne("Api_ProjectManagement.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("Tareas")
                        .HasForeignKey("IdUsuario")
                        .HasConstraintName("Fk_Tareas_Refe_Usuario");

                    b.Navigation("IdArchivoNavigation");

                    b.Navigation("IdEstadoNavigation");

                    b.Navigation("IdPrioridadNavigation");

                    b.Navigation("IdProyectoNavigation");

                    b.Navigation("IdTareaPadreNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("Api_ProjectManagement.Models.UsuariosRole", b =>
                {
                    b.HasOne("Api_ProjectManagement.Models.Role", "IdRolNavigation")
                        .WithMany("UsuariosRoles")
                        .HasForeignKey("IdRol")
                        .HasConstraintName("Fk_UsuarioRol_Refe_Rol");

                    b.HasOne("Api_ProjectManagement.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("UsuariosRoles")
                        .HasForeignKey("IdUsuario")
                        .HasConstraintName("Fk_UsuarioRol_Refe_Usuario");

                    b.Navigation("IdRolNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("Api_ProjectManagement.Models.Archivo", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("Tareas");
                });

            modelBuilder.Entity("Api_ProjectManagement.Models.Estado", b =>
                {
                    b.Navigation("Proyectos");

                    b.Navigation("Tareas");
                });

            modelBuilder.Entity("Api_ProjectManagement.Models.Prioridad", b =>
                {
                    b.Navigation("Tareas");
                });

            modelBuilder.Entity("Api_ProjectManagement.Models.Proyecto", b =>
                {
                    b.Navigation("ProyectoUsuarios");

                    b.Navigation("Tareas");
                });

            modelBuilder.Entity("Api_ProjectManagement.Models.Role", b =>
                {
                    b.Navigation("UsuariosRoles");
                });

            modelBuilder.Entity("Api_ProjectManagement.Models.Tarea", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("HistorialTareas");

                    b.Navigation("InverseIdTareaPadreNavigation");
                });

            modelBuilder.Entity("Api_ProjectManagement.Models.Usuario", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("HistorialTareas");

                    b.Navigation("ProyectoUsuarios");

                    b.Navigation("Proyectos");

                    b.Navigation("Tareas");

                    b.Navigation("UsuariosRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
